### PR TITLE
ENH: Add versioneer to project

### PR DESCRIPTION
**Pull request by ElDeveloper**
Once we start tagging the repo we should be able to track versions with the
versioneer.

### CODE REVIEW

**Comment by ElDeveloper** [comment]
`_version.py` and `versioneer.py` can be ignored from the review since those are automatically created by versioneer.

**Review by antgonza — APPROVED** [review]
Looks good to me; should we wait for a 2nd reviewer?

**Review by charles-cowart — APPROVED** [review]
Everything looks in order. It looks like watermark is there to support versioning.

**Comment by ElDeveloper** [comment]
Yes, I figured now that the project is versioned we can track that with the %watermark magic. Thanks both.

**Pull request merged**
