### PR TITLE
Multiproject plate support, updated blanks handling

### PR DESCRIPTION
**Pull request by AmandaBirmingham**
This work has been reviewed in smaller pieces as it was pushed into the multiproject_plate branch.  Now that it is complete, we're ready to get it into the main branch :)

### CODE REVIEW

**Comment by antgonza** [comment]
Thank you @AmandaBirmingham, just to confirm; all this code has been reviewed before and we just need to merge it the main branch, right?

**Comment by AmandaBirmingham** [comment]
@antgonza, yes, this is all the stuff we were just reviewing in the multiproject_plate branch.  The **ONLY** thing that hasn't already had eyes on it was that, after merging @charles-cowart's new `load_sample_sheet` code, I had to add one more sample sheet type to the list in that function (there are tests for this sample sheet type, so they fail without it :).

Screenshot 2024-11-07 at 4 14 38 PM

**Comment by AmandaBirmingham** [comment]
@antgonza However, I note that the current main branch of mg-scripts won't work with this version of metagenomics_pooling_notebook until the PR for mg-scripts goes in.  How do you handle these chicken/egg situations?

**Comment by charles-cowart** [comment]
> Thank you @AmandaBirmingham, just to confirm; all this code has been reviewed before and we just need to merge it the main branch, right?

For what it's worth, it has my thumbs-up.

**Comment by antgonza** [comment]
The way we handle it is that we don't deploy this version until all the repos are working nice with each other. I'm merging now.

**Pull request merged**
