### PR TITLE
ENH: Add watermark to notebooks

### PR DESCRIPTION
**Pull request by ElDeveloper**
This will help keep track of what versions were installed when the
notebooks were run.

https://github.com/rasbt/watermark

### CODE REVIEW

**Review by antgonza — APPROVED** [review]
Really nice. I guess is would be nice to add something like this to new projects in https://github.com/knightlab-analyses, no? 

Do we need another reviewer?

**Comment by ElDeveloper** [comment]
Thanks for reviewing. One review should be fine, these are rather straightforward PRs.

**Review by charles-cowart — APPROVED** [review]
Sneaking a review in before the expected merge. It looks good, and interesting!

**Comment by ElDeveloper** [comment]
Thanks both!

**Pull request merged**
