### PR TITLE
STY: Flake8tify the codebase

### LINKED ISSUE #5: Enable flake8
It’s already in the actions script but once that section is not commented we’ll need to fix a lot of PEP8 issues. If everyone is ok with that let’s add it after the `amplicon-pooling` branch is merged.

### PR DESCRIPTION
**Pull request by ElDeveloper**
Fixes #5

### CODE REVIEW

**Comment by ElDeveloper** [comment]
@unique-identifier @charles-cowart any chance you could review/merge this PR? Most of the changes were done with autopep8. Only non-automatic changes that I made were breaking long lines manually and adding some missing imports to the notebooks resulting from removing imports in metapool (because most notebooks run `from metapool.metapool import *` oh well).

**Comment by unique-identifier** [comment]
Will do!

**Comment by ElDeveloper** [comment]
Thanks so much!

**Review by unique-identifier — APPROVED** [review]
Everything looks good! Sorry for the delay.

**Comment by charles-cowart** [comment]
@ElDeveloper I got my 'Charles-cowart' account back. If you don't mind giving me write access to this repo, I can merge now or after Antonio's reviewed it. Thanks!

**Review by antgonza — APPROVED** [review]

**Comment by ElDeveloper** [comment]
Sent!

**Comment by ElDeveloper** [comment]
Thanks both!

**Comment by ElDeveloper** [comment]
Thanks so much for the prompt review. Can you merge the PR?

**Comment by charles-cowart** [comment]
@ElDeveloper Unless I missed something Antonio already merged it.

**Pull request merged**
