### PR TITLE
seqpro updated to pass through columns

### PR DESCRIPTION
**Pull request by charles-cowart**
seqpro updated to pass through columns specific to a particular KLSampleSheet child-type.

A little bit of refactoring and cleaning up is needed. Some of the changes to existing functions are kludgy. Column names for other sample-sheet types should also be defined. A few new tests are also in order.

### CODE REVIEW

**Comment by charles-cowart** [comment]
This will be cleaned up before Monday morning. You guys can see where I'm going with this. existing tests have been updated and should work correctly. The list of columns that will be passed through in a given prep will be defined by the type of sample-sheet given to seqpro.

**Comment by charles-cowart** [comment]
The first line of the prep-info file generated from 15288:
sample_plate	well_id_384	i7_index_id	index	i5_index_id	index2	sample_name	experiment_design_description	syndna_pool_number	well_description	library_construction_protocol	platform	run_center	run_date	run_prefix	mass_syndna_input_ng	vol_extracted_elution_ul	extracted_gdna_concentration_ng_ul	sequencing_meth	center_name	center_project_name	instrument_model	runid	lane	sample_project	raw_reads_r1r2	total_biological_reads_r1r2	non_host_reads	quality_filtered_reads_r1r2	fraction_passing_quality_filter	fraction_non_human
NPH_15288_P2_diluted	A1	iTru7_206_10	AGGTCACT	iTru5_01_A	TTGTCGGT	359180364	fat isolate sequencing	pool1	NPH_15288_P2_diluted.359180364.A1	Knight Lab Kapa HyperPlus	Illumina	KLM	2024-01-29	359180364_S1_L001	0.2503031	70	94.454	sequencing by synthesis	UCSD	NPH	Illumina iSeq	20240129_FS10001773_87_BTR99519-2335	1	NPH	42140	31502.0	NA	42140.1.0	NA

**Comment by charles-cowart** [comment]
> The first line of the prep-info file generated from 15288:
> sample_plate well_id_384 i7_index_id index i5_index_id index2 sample_name experiment_design_description syndna_pool_number well_description library_construction_protocol platform run_center run_date run_prefix mass_syndna_input_ng vol_extracted_elution_ul extracted_gdna_concentration_ng_ul sequencing_meth center_name center_project_name instrument_model runid lane sample_project raw_reads_r1r2 total_biological_reads_r1r2 non_host_reads quality_filtered_reads_r1r2 fraction_passing_quality_filter fraction_non_human
> NPH_15288_P2_diluted A1 iTru7_206_10 AGGTCACT iTru5_01_A TTGTCGGT 359180364 fat isolate sequencing pool1 NPH_15288_P2_diluted.359180364.A1 Knight Lab Kapa HyperPlus Illumina KLM 2024-01-29 359180364_S1_L001 0.2503031 70 94.454 sequencing by synthesis UCSD NPH Illumina iSeq 20240129_FS10001773_87_BTR99519-2335 1 NPH 42140 31502.0 NA 42140.1.0 NA

Just a quick FYI: the actual numbers may be slightly off for this sample; I copied the raw fastq files and renamed them as the human-filtered and adapter trimmed files for testing purposes. The counts will likely be off by a small amount.

**Review by antgonza — APPROVED** [review]
Looks good to me, no comments.

**Review by mmbryant23 — APPROVED** [review]

**Pull request merged**
