### PR TITLE
Additional review changes

### PR DESCRIPTION
**Pull request by ElDeveloper**
These changes were requested by MacKenzie, in brief: adds some missing columns to the prep, checks for primer plate numbers, checks that sample plates don't contain spaces, reorders some of the plating metadata fields, and adds her e-mail to the contacts list.

Depends on #7 so merge that first.

### CODE REVIEW

**Comment by ElDeveloper** [comment]
Make sure you review/merge #7 before merging this one.

**Comment by ElDeveloper** [comment]
@charles-cowart @antgonza if any of you could review and merge this PR that would be excellent.

**Comment by charles-cowart** [comment]
will do!

**Review by charles-cowart — APPROVED** [review]
Everything looks good to me.

**Comment by ElDeveloper** [comment]
Thanks so much @charles-cowart

**Pull request merged**
