### PR TITLE
Add support for parsing sample sheets with empty lines

### PR DESCRIPTION
**Pull request by ElDeveloper**
Turns out this is a valid format, but since we support comments we needed to add a check there. Already was documented here:
https://github.com/clintval/sample-sheet/issues/46

### CODE REVIEW

**Review by charles-cowart — APPROVED** [review]
Looks good.

**Comment by charles-cowart** [comment]
@ElDeveloper merged code failed testing in the new Github CI. I'll revert for now. The nature of this error escapes me:
https://github.com/biocore/metagenomics_pooling_notebook/runs/3653593683?check_suite_focus=true#step:9:38

**Comment by charles-cowart** [comment]
@ElDeveloper confirmed coveralls tests succeeded, and your changes are in the lastest master. We should be good with this one.

**Comment by ElDeveloper** [comment]
Thanks so much!

**Pull request merged**
