### PR TITLE
Add tests dp

### PR DESCRIPTION
**Pull request by dpear**
Moves functions out of the jupyter notebook and includes basic test cases for these functions.

### CODE REVIEW

**Comment by charles-cowart** [comment]
@dpear Hi Daniella! I've gone ahead and redirected your PR to our new branch. Since many people are working on changes and additions at the same time, we'll be working from a copy of the master branch called 'dev'. That way we'll be able to test that all of the changes work well together before updating the master branch.

Whenever you're available, I can help you update your fork of metapool and your local copy so that you have a copy of this dev branch.

**Comment by RodolfoSalido** [comment]
Hi Charlie,
I’m trying to take over getting this PR into the repository and resolving some of the syncing issues across plate_replication, synDNA, and matrix_tube development branches. 

I’ve been messing around with GitHub to try to rebase(?) the upstream of my fork to biocore:metagenomics_pooling_notebook/dev branch, but I’m not sure I’m doing this correctly. 

Can I get some help with this? We also need to merge Dani’s PR with the dev branch so that I can resolve some of the issues that are pending.

**Comment by RodolfoSalido** [comment]
Bumping this. I think I was able to checkout the biocore:metagenomics_pooling_notebook/dev branch on my local machine. Can we get this PR merged into the dev branch so that I can work on it?

**Comment by charles-cowart** [comment]
@RodolfoSalido This PR has 52 changed files, which is a little over double the highest number I've ever issued or reviewed for a PR. It also contains a number of files like .DS_Store which shouldn't be there. I apologize for the delay but please let me make one pass on this PR first to clean up those files and I'll approve and merge it. I can do this later this evening.

**Comment by AmandaBirmingham** [comment]
Personal opinion: A much lower bar for code review is required when pushing into the dev branch :)

**Comment by charles-cowart** [comment]
> Personal opinion: A much lower bar for code review is required when pushing into the dev branch :)

This is a little too low even for that, IMHO. :) However I do believe in consensus.

**Review by charles-cowart — APPROVED** [review]
If it wasn't obvious.DS_Store files should be removed and all code should have tests before merging into main branch.

**Comment by RodolfoSalido** [comment]
Sounds good. I added .DS_Store to .gitignore recently. I'm also making sure that all new functions will have unit tests.

**Pull request merged**
