### PR TITLE
Cleaned up test_data input and output for notebook templates

### PR DESCRIPTION
**Pull request by RodolfoSalido**
Generated new output files for iSeqnormpool because we changed default behavior to normalized pooling on 'Raw Reads' and the previous output file was not reflecting this. Separated the test_ouput files for the matrix notebook and the legacy notebook (plate map based) because they were overwriting the same output file with small sample_name discrepancies that resulted in unstable changes to files in repository depending on which notebook was being run last before committing changes. Fixed a small issue with katharoseq barcodes being present in matrix tube template when we instead are trying to default to a metagenomic template with no katharoseq samples.

### CODE REVIEW

**Review by AmandaBirmingham — CHANGES_REQUESTED** [review]
Wow, this is a lot more than I thought it would be--I was only expecting changes to the `notebooks/test_output/Pooling/YYYY_MM_DD_Celeste_Adaptation_16_17_18_21_iSeqnormpool.csv` file! But I think I understand the rationale for the additional files.  One request: instead of adding the extra tube ids (that would be the katharoseq control tube ids if this notebook were using katharoseq but it isn't blah blah blah) into the `blanks_1.tsv` file, could you please create a NEW blanks file in that same directory to hold those ids?  This will both test that the code correctly picks up multiple files, and will also make it easy for us to take them back OUT when we get to the point of wanting to add and test the katharoseq functionality in this notebook.

**Comment by RodolfoSalido** [comment]
I actually deleted duplicated matrix tube barcodes from the blanks_1.tsv file (not sure how they got introduced in the first plate), and changed the tube_ids that were katharoseq related from the matrix_tube_plate_scan file (2022_summer_Celeste_Adaptation_21_plate_map.tsv) and replaced them with blank tube_ids that I found in the blanks_1.tsv file. I think that is a clean fix. If we want to add katharoseq test functionality in the future, the katharoseq_tube_ids.tsv file in the katharoseq directory should still hold the tube_ids that I replaced, and they would not be anywhere else.

**Review by AmandaBirmingham — APPROVED** [review]
I approve these changes, and, since they are all in the notebooks and their ad-hoc test files, I think it is low-risk to merge into master.  @charles-cowart, are you on board with that?

**Review by charles-cowart — APPROVED** [review]
Approved.

**Comment by charles-cowart** [comment]
> I approve these changes, and, since they are all in the notebooks and their ad-hoc test files, I think it is low-risk to merge into master. @charles-cowart, are you on board with that?

Agreed it's low-risk so long as the users of the notebooks are in the loop.

**Pull request merged**
