### PR TITLE
Update error text for parsing run ID

### PR DESCRIPTION
**Pull request by wasade**
cc @ElDeveloper

### CODE REVIEW

**Comment by ElDeveloper** [comment]
Looks good, thanks! Can you add a test for that exception? Otherwise looks good to go. Thanks so much for addressing so promptly! 😃

**Comment by wasade** [comment]
A test was added in #65 to assert parsing of an iSeq run ID, is there a different test that should be added here?

**Comment by ElDeveloper** [comment]
Yes, I was thinking about a test that checks for the correct exception error message depending on the malformed input.

**Comment by ElDeveloper** [comment]
Thanks so much!

**Pull request merged**
