### PR TITLE
Update metadata_samples_plasmid_sequences.txt

### PR DESCRIPTION
**Pull request by justinshaffer**
Added column for sample input weights and updated pool variable name

### CODE REVIEW

**Comment by charles-cowart** [comment]
@antgonza This looks like it goes hand in hand with https://github.com/biocore/metagenomics_pooling_notebook/pull/107

**Comment by antgonza** [comment]
... interestingly the tests (are there any tests?) didn't fail even if the changes are in different PRs.

**Comment by charles-cowart** [comment]
> ... interestingly the tests (are there any tests?) didn't fail even if the changes are in different PRs.

Yeah I'm not sure there's any tests for calculate_coefficients.py. I don't think I've ever touched or debugged any code in that file ever. I'll do some investigating.

**Comment by charles-cowart** [comment]
> > ... interestingly the tests (are there any tests?) didn't fail even if the changes are in different PRs.
> 
> Yeah I'm not sure there's any tests for calculate_coefficients.py. I don't think I've ever touched or debugged any code in that file ever. I'll do some investigating.

Actually that file does not exist in the main metapool repo. I think we will need to work with Justin to get, review, pull in, and add tests for this new code before accepting this PR. I think we can close this one as it is.

**Review by charles-cowart — APPROVED** [review]
Approved.

**Pull request merged**
